export const ActionTypes = {
  SET_JOURNEYS: 'SET_JOURNEYS',
  SELECTED_JOURNEY: 'SELECTED_JOURNEY',
  REMOVE_SELECTED_JOURNEY: 'REMOVE_SELECTED_JOURNEY',
  SET_DRAFT: 'SET_DRAFT',
  REMOVE_DRAFT: 'REMOVE_DRAFT',
}
